name: fetch-repository-stats
concurrency: fetch-repository-stats

on:
  schedule:
    - cron: "0 23 * * *"
  workflow_dispatch:

jobs:
  run-ghrs-with-matrix:
    name: repostats
    runs-on: ubuntu-latest
    strategy:
      matrix:
        statsRepo: 
          - 'touk/nussknacker'
          - 'touk/nussknacker-installation-example'
          - 'touk/nussknacker-quickstart'
          - 'touk/nussknacker-helm'
          - 'touk/nussknacker-sample-components'
          - 'touk/nussknacker-sample-helpers'
          - 'touk/nussknacker-flink-compatibility'
          - 'touk/nussknacker-elasticsearch-example'
          - 'touk/nussknacker-card-example'
          - 'touk/nussknacker-twitter-example'
          - 'touk/nussknacker-credit-rating-example'
          - 'touk/nussknacker-batch-example'
          - 'touk/nussknacker-iceberg-example'
          - 'touk/recommendations-showcase-notebook'
      # Do not cancel&fail all remaining jobs upon first job failure.
      fail-fast: false
      # Help avoid commit conflicts. Note(JP): this should not be
      # necessary anymore, feedback appreciated
      max-parallel: 1
    steps:
      - name: run-ghrs
        uses: jgehrcke/github-repo-stats@v1.4.2
        with:
          repository: ${{ matrix.statsRepo }}
          ghtoken: ${{ secrets.GHRS_GITHUB_API_TOKEN }}
