name: fetch-repository-stats
concurrency: fetch-repository-stats

on:
  schedule:
    - cron: "0 23 * * *"
  workflow_dispatch:

jobs:
  run-ghrs-with-matrix:
    name: repostats-for-nice-projects
    runs-on: ubuntu-latest
    strategy:
      matrix:
        statsRepo: ['touk/nussknacker', 'touk/nussknacker-quickstart', 'touk/nussknacker-sample-components', 'touk/nussknacker-helm', 'touk/nussknacker-flink-compatibility', 'touk/nussknacker-elasticsearch-example', 'touk/nussknacker-card-example', 'touk/nussknacker-twitter-example']
      # Do not cancel&fail all remaining jobs upon first job failure.
      fail-fast: false
      # Help avoid commit conflicts. Note(JP): this should not be
      # necessary anymore, feedback appreciated
      max-parallel: 1
    steps:
      - name: run-ghrs
        uses: jgehrcke/github-repo-stats@RELEASE
        with:
          repository: ${{ matrix.statsRepo }}
          ghtoken: ${{ secrets.ghrs_github_api_token }}
